#!/bin/bash

# functions
usage() {
    echo "Open a VPN connection to the given host gateway url.
Usage: connect [options...] <url>
    -u  The VPN username
    -p  The VPN password
    -h  Usage
    exit 0;
    "
}

while getopts ":u:p:h" arg; do
    case $arg in
        u)
          USERNAME=${OPTARG}
          ;;
        p)
          PASSWORD=${OPTARG}
          ;;
        *)
          usage
          ;;
    esac
done

shift $((OPTIND-1))
HOST=$1

if [[ -z ${HOST} ]]; then
    echo "Failure: no VPN gateway url provided"
    exit 1
fi

if [[ -z ${USERNAME} ]]; then
    echo "Failure: no VPN username provided"
    exit 1
fi

if [[ -z ${PASSWORD} ]]; then
    echo "Failure: no VPN password provided"
    exit 1
fi

bash -c "echo -n ${PASSWORD} | openconnect -u${USERNAME} --passwd-on-stdin --script-tun --non-inter --script /usr/bin/vpn_script ${HOST}" &

sleep 5
